import { TOKEN_KINDS } from "./token-kinds.js";

export const KEYWORDS = new Map([
  ["set", TOKEN_KINDS.SET],
  ["print", TOKEN_KINDS.PRINT],
  ["create", TOKEN_KINDS.CREATE],
  ["take", TOKEN_KINDS.TAKE],
  ["always", TOKEN_KINDS.ALWAYS],
  ["is", TOKEN_KINDS.IS],
  ["result", TOKEN_KINDS.RESULT],
  ["round", TOKEN_KINDS.ROUND],
  ["floor", TOKEN_KINDS.FLOOR],
  ["ceil", TOKEN_KINDS.CEIL],
  ["fixed", TOKEN_KINDS.FIXED],
  ["to", TOKEN_KINDS.TO],
  ["the", TOKEN_KINDS.THE],
  ["when", TOKEN_KINDS.WHEN],
  ["in", TOKEN_KINDS.IN],
  ["case", TOKEN_KINDS.CASE],
  ["otherwise", TOKEN_KINDS.OTHERWISE],
  ["check", TOKEN_KINDS.CHECK],
  ["default", TOKEN_KINDS.DEFAULT],
  ["for", TOKEN_KINDS.FOR],
  ["each", TOKEN_KINDS.EACH],
  ["repeat", TOKEN_KINDS.REPEAT],
  ["times", TOKEN_KINDS.TIMES],
  ["keep", TOKEN_KINDS.KEEP],
  ["doing", TOKEN_KINDS.DOING],
  ["this", TOKEN_KINDS.THIS],
  ["while", TOKEN_KINDS.WHILE],
  ["until", TOKEN_KINDS.UNTIL],
  ["list", TOKEN_KINDS.LIST],
  ["and", TOKEN_KINDS.AND],
  ["greater", TOKEN_KINDS.GREATER],
  ["less", TOKEN_KINDS.LESS],
  ["equal", TOKEN_KINDS.EQUAL],
  ["not", TOKEN_KINDS.NOT],
  ["than", TOKEN_KINDS.THAN],
  ["or", TOKEN_KINDS.OR],
  ["with", TOKEN_KINDS.WITH],
  ["contains", TOKEN_KINDS.CONTAINS],
  ["starts", TOKEN_KINDS.STARTS],
  ["ends", TOKEN_KINDS.ENDS],
  ["joined", TOKEN_KINDS.JOINED]
]);

export const BOOLEAN_LITERALS = new Map([
  ["true", true],
  ["false", false],
  ["yes", true],
  ["no", false],
  ["on", true],
  ["off", false],
  ["y", true],
  ["n", false]
]);
