import { TOKEN_KINDS } from "./token-kinds.js";

export const KEYWORDS = new Map([
  ["set", TOKEN_KINDS.SET],
  ["print", TOKEN_KINDS.PRINT],
  ["how", TOKEN_KINDS.HOW],
  ["do", TOKEN_KINDS.DO],
  ["share", TOKEN_KINDS.SHARE],
  ["use", TOKEN_KINDS.USE],
  ["wait", TOKEN_KINDS.WAIT],
  ["try", TOKEN_KINDS.TRY],
  ["ensure", TOKEN_KINDS.ENSURE],
  ["verify", TOKEN_KINDS.VERIFY],
  ["return", TOKEN_KINDS.RETURN],
  ["returns", TOKEN_KINDS.RETURNS],
  ["create", TOKEN_KINDS.CREATE],
  ["define", TOKEN_KINDS.DEFINE],
  ["type", TOKEN_KINDS.TYPE],
  ["ask", TOKEN_KINDS.ASK],
  ["take", TOKEN_KINDS.TAKE],
  ["always", TOKEN_KINDS.ALWAYS],
  ["is", TOKEN_KINDS.IS],
  ["result", TOKEN_KINDS.RESULT],
  ["round", TOKEN_KINDS.ROUND],
  ["floor", TOKEN_KINDS.FLOOR],
  ["ceil", TOKEN_KINDS.CEIL],
  ["fixed", TOKEN_KINDS.FIXED],
  ["to", TOKEN_KINDS.TO],
  ["the", TOKEN_KINDS.THE],
  ["when", TOKEN_KINDS.WHEN],
  ["in", TOKEN_KINDS.IN],
  ["case", TOKEN_KINDS.CASE],
  ["otherwise", TOKEN_KINDS.OTHERWISE],
  ["check", TOKEN_KINDS.CHECK],
  ["default", TOKEN_KINDS.DEFAULT],
  ["for", TOKEN_KINDS.FOR],
  ["each", TOKEN_KINDS.EACH],
  ["repeat", TOKEN_KINDS.REPEAT],
  ["times", TOKEN_KINDS.TIMES],
  ["break", TOKEN_KINDS.BREAK],
  ["continue", TOKEN_KINDS.CONTINUE],
  ["keep", TOKEN_KINDS.KEEP],
  ["doing", TOKEN_KINDS.DOING],
  ["this", TOKEN_KINDS.THIS],
  ["its", TOKEN_KINDS.ITS],
  ["itself", TOKEN_KINDS.ITSELF],
  ["super", TOKEN_KINDS.SUPER],
  ["while", TOKEN_KINDS.WHILE],
  ["until", TOKEN_KINDS.UNTIL],
  ["list", TOKEN_KINDS.LIST],
  ["private", TOKEN_KINDS.PRIVATE],
  ["protected", TOKEN_KINDS.PROTECTED],
  ["public", TOKEN_KINDS.PUBLIC],
  ["and", TOKEN_KINDS.AND],
  ["greater", TOKEN_KINDS.GREATER],
  ["less", TOKEN_KINDS.LESS],
  ["equal", TOKEN_KINDS.EQUAL],
  ["not", TOKEN_KINDS.NOT],
  ["than", TOKEN_KINDS.THAN],
  ["or", TOKEN_KINDS.OR],
  ["with", TOKEN_KINDS.WITH],
  ["contains", TOKEN_KINDS.CONTAINS],
  ["starts", TOKEN_KINDS.STARTS],
  ["ends", TOKEN_KINDS.ENDS],
  ["joined", TOKEN_KINDS.JOINED]
]);

export const BOOLEAN_LITERALS = new Map([
  ["true", true],
  ["false", false],
  ["yes", true],
  ["no", false],
  ["on", true],
  ["off", false],
  ["y", true],
  ["n", false]
]);
