import test from "node:test";
import assert from "node:assert/strict";

import { TOKEN_KINDS, lex } from "../../src/index.js";

test("lexer tokenizes collection declarations, records, and pipeline operators", () => {
  const source = [
    "Create a List called users defined as:",
    '    - {Name: "Alice", Age: 25, Active: Yes}',
    "Create a List called adults from users where Age >= 20 select Name.",
    "Take users:",
    "    Then filter where Active is Yes",
    "    Then sort by Age descending",
    "    Then take the first 2 items",
    "    Then select {Name, Age}",
    "    Then save to senior users as a list"
  ].join("\n");

  const kinds = lex(source).map((token) => token.kind);

  assert.deepEqual(kinds, [
    TOKEN_KINDS.CREATE,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.LIST,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.COLON,
    TOKEN_KINDS.NEWLINE,
    TOKEN_KINDS.INDENT,
    TOKEN_KINDS.MINUS,
    TOKEN_KINDS.LBRACE,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.COLON,
    TOKEN_KINDS.STRING,
    TOKEN_KINDS.COMMA,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.COLON,
    TOKEN_KINDS.NUMBER,
    TOKEN_KINDS.COMMA,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.COLON,
    TOKEN_KINDS.BOOLEAN,
    TOKEN_KINDS.RBRACE,
    TOKEN_KINDS.NEWLINE,
    TOKEN_KINDS.DEDENT,
    TOKEN_KINDS.CREATE,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.LIST,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.GTE,
    TOKEN_KINDS.NUMBER,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.DOT,
    TOKEN_KINDS.NEWLINE,
    TOKEN_KINDS.TAKE,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.COLON,
    TOKEN_KINDS.NEWLINE,
    TOKEN_KINDS.INDENT,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.IS,
    TOKEN_KINDS.BOOLEAN,
    TOKEN_KINDS.NEWLINE,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.NEWLINE,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.TAKE,
    TOKEN_KINDS.THE,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.NUMBER,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.NEWLINE,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.LBRACE,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.COMMA,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.RBRACE,
    TOKEN_KINDS.NEWLINE,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.TO,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.WORD,
    TOKEN_KINDS.LIST,
    TOKEN_KINDS.DEDENT,
    TOKEN_KINDS.EOF
  ]);
});
